import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import Community from "../components/community";
import Map from "../components/map";
import Menu from "../components/menu";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="fonts/DIN\ Condensed\ Bold.ttf" as="font" />
        <link href="/fonts/GillSans.ttc" as="font" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <Community />
        <Map />
        <Menu />
      </main>
    </div>
  );
}
