import Head from "next/head";
import React, { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Hero from "../components/hero";
import Community from "../components/community";
import Map from "../components/map";
import Menu from "../components/menu";

export default function Home() {
  // const [offsetY, setOffsetY] = useState(0);
  // const handleScroll = () => setOffsetY(window.pageYOffset);

  // useEffect(() => {
  //   window.addEventListener("scroll", handleScroll);

  //   return () => window.removeEventListener("scroll", handleScroll);
  // }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="fonts/DIN\ Condensed\ Bold.ttf" as="font" />
        <link href="/fonts/GillSans.ttc" as="font" />
      </Head>

      <main className={styles.main}>
        {/* <div
          className=""
          style={{ transform: `translateY(-${offsetY * 0.3}px)` }}
        ></div> */}
        <Hero />
        <Community />
        <Map />
        <Menu />
      </main>
    </div>
  );
}
